#!/usr/bin/env bash

wget -O home/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
rm $HOME/.bashrc $HOME/.profile $HOME/.bash_logout
sudo apt-get update
# TODO: See if cmake is necessary
sudo apt-get install git make stow python-dev cmake build-essentials
