#!/usr/bin/env python

import sys
import re

stnc_pat = re.compile(r'([^.!;?]*([.!;?]|\n\n)(\s|$))',
                      re.MULTILINE)

def sentences(string):
    "Find sentences and split their punctuation."
    yield from (match.groups()[0]
                for match in re.finditer(stnc_pat, string))
    
def unsentences(sentences):
    return '\n'.join(sentences)

def normalize(string):
    return ' '.join(string.split('\n')).strip()

def wrap(string, at):
    pieces = []
    while len(string) > at:
        largest = string[:at]
        piece, _ = largest.rsplit(maxsplit=1)
        pieces.append(piece.strip())
        string = string[len(piece):]
    pieces.append(string.strip())
    return '\n'.join(pieces)

def paragraphs(string):
    yield from string.split('\n\n')
    
def unparagraphs(paragraphs):
    return '\n\n'.join(paragraphs)

def reformat(string, wrap_at=79):
    out_pars = []
    for par in paragraphs(string):
        out_stncs = []
        for stnc in sentences(par):
            out_stncs.append(wrap(normalize(stnc), wrap_at))
        out_pars.append(unsentences(out_stncs))
    return unparagraphs(out_pars)

def main():
    sys.stdout.write(reformat(sys.stdin.read()))

if __name__ == "__main__":
    main()
