#!/usr/bin/env bash

USAGE_MSG="$(basename $0) NOTE [ARGS]"
HELP_MSG="Process note using pandoc.  Additional args passed on."
if [ -n "$ECHO_HELP" ]; then
    echo "    $USAGE_MSG"
    echo "        $HELP_MSG"
    exit 0
fi

if [ -z $1 ]; then
    echo "Insufficient arguments."  >&2
    echo "Usage: $USAGE_MSG"        >&2
    exit 1
fi

note=$(find_note $1)
shift

if [ -z $PANDOC_OPTS ]; then
    PANDOC_OPTS=""
    if hash pandoc-citeproc; then
        PANDOC_OPTS="$PANDOC_OPTS --filter pandoc-citeproc"
    fi
fi

pandoc $PANDOC_OPTS "$@" $note
