#!/usr/bin/env bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) ITEM# TEXT"
    echo "      appends TEXT and marks task NUMBER as complete."
    echo ""
    exit
}

item=$1
shift
text=$*

$TODO_FULL_SH doand $item app $text
