#!/usr/bin/env bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) ITEM# ACTION ARGS"
    echo "      marks task NUMBER as complete after"
    echo "      doing ACTION NUMBER ARGS"
    exit
}

item=$1
shift
pre_action=$1
shift
args=$*

$TODO_FULL_SH $pre_action $item $args
$TODO_FULL_SH do $item
