#!/usr/bin/env bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) ITEM# TIME"
    echo "      update the et: tag and mark as complete."
    echo ""
    exit
}

item=$1
shift
et=$1

$TODO_FULL_SH doand $item et $et

