#!/bin/bash
# https://raw.githubusercontent.com/mbrubeck/todo.txt-cli/master/todo.actions.d/edit
action=$1
shift

[ "$action" = "usage" ] && {
    echo "    $(basename $0) [FILE]"
    echo "      Open \$TODO_DIR/\$FILE in \$EDITOR."
    echo "      If \$FILE is not given, defaults to \$TODO_FILE."
    echo ""
    exit
}

if [ -z "$1" ]; then
    FILE=$TODO_FILE
else
    FILE=$TODO_DIR/${1%.txt}.txt
fi

if [ -n "$EDITOR" ]; then
    $EDITOR $FILE
else
    echo "Error: The \$EDITOR environment variable is not set"
    exit 1
fi
